nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: []
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        allow_origin: ['*']
        allow_headers: ['X-Custom-Auth']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
        max_age: 3600
