vich_uploader:
    db_driver: orm

    mappings:
        celestial_body_pictures:
            uri_prefix: /images/pictures
            upload_destination: '%kernel.project_dir%/public/images/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        celestial_body_icons:
            uri_prefix: /images/icons
            upload_destination: '%kernel.project_dir%/public/images/icons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
